export const ACTIVE = {
    TASK_SUB: 'TASK_SUB',
    IDEA_SUB: 'IDEA_SUB',
    RANDOM_THOUGHT_SUB: 'RANDOM_THOUGHT_SUB',
    TASK_ADD: 'TASK_ADD',
    IDEA_ADD: 'IDEA_ADD',
    RANDOM_THOUGHT_ADD: 'RANDOM_THOUGHT_ADD'
}

export const ARCHIVED = {
    ARCHIVED_TASK_SUB: 'ARCHIVED_TASK_SUB',
    ARCHIVED_IDEA_SUB: 'ARCHIVED_IDEA_SUB',
    ARCHIVED_RANDOM_THOUGHT_SUB: 'ARCHIVED_RANDOM_THOUGHT_SUB',
    ARCHIVED_TASK_ADD: 'ARCHIVED_TASK_ADD',
    ARCHIVED_IDEA_ADD: 'ARCHIVED_IDEA_ADD',
    ARCHIVED_RANDOM_THOUGHT_ADD: 'ARCHIVED_RANDOM_THOUGHT_ADD'
}